// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHCFUeh4QTMaq_dgDmdYuIr4YruuNBFss',
    appId: '1:127630119989:web:364e55019e27870d430d7c',
    messagingSenderId: '127630119989',
    projectId: 'cuacaapp-596a5',
    authDomain: 'cuacaapp-596a5.firebaseapp.com',
    storageBucket: 'cuacaapp-596a5.firebasestorage.app',
    measurementId: 'G-Y7CCN48X3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC0EXq9DZcACjbAhdXcut2OYbH6-MiOyY',
    appId: '1:127630119989:android:a3c6401fd032ee6e430d7c',
    messagingSenderId: '127630119989',
    projectId: 'cuacaapp-596a5',
    storageBucket: 'cuacaapp-596a5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHCFUeh4QTMaq_dgDmdYuIr4YruuNBFss',
    appId: '1:127630119989:web:07bda4351234dd81430d7c',
    messagingSenderId: '127630119989',
    projectId: 'cuacaapp-596a5',
    authDomain: 'cuacaapp-596a5.firebaseapp.com',
    storageBucket: 'cuacaapp-596a5.firebasestorage.app',
    measurementId: 'G-RK9HL64NGT',
  );

}